# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 王树东
title: 嵌入式/蓝牙/tws耳机 软件开发
email: wangshu_d@126.com
phone: 15818738013
website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  shyden-wang
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 关于我
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - 10年+嵌入式软件开发经验，专注于蓝牙音频与物联网方案开发。
  - 精通杰理7016系列蓝牙平台深度开发，在翻译耳机领域积累了丰富的量产经验。
  - 具备从需求分析到量产交付的全流程项目经验，累计主导/参与超过5款 tws 翻译耳机量产，20+ USB、音频、2.4g消费类电子产品的量产落地。
  - 善于将复杂需求转化为稳定可靠的产品方案，擅长跨团队（产品、APP、硬件、算法、生产）协作与解决开发、量产过程中的技术难题。
content:
  - title: 专业技能 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "语言"  
        description: | # this will include new lines to allow paragraphs
          - 精通 C 语言，熟练掌握嵌入式系统的开发、生产流程。
          - 熟悉汇编语言、C++、Python 等，能完成简单的开发、维护和调试。
      - layout: left
        title: "芯片及架构"
        description: | # this will include new lines to allow paragraphs
          熟练使用常见芯片架构的开发，包括：ARM M0、M3、M4, RISC-V 等，使用的芯片包括新唐、ST（国产芯片）、Telink、Nordic、瑞昱等。
      - layout: left
        title: "知识栈"
        description: |
          - 熟悉经典蓝牙及 BLE 协议，能够基于平台做深入的应用开发、协议开发及 2.4G 开发。
          - 熟悉基于 USB Audio 的开发，能够独立从 0 开始实现 USB + Codec 的音频方案。
          - 熟练使用芯片各个外设，各种常见总线协议，包括但不限于：UART、USB、I2C、SPI、I2S 等。
          - 熟悉 UCOS、RT-Thread 等操作系统，了解其调度切换原理（目前正在学习代码实现过程），能够实现基于应用的开发。
          - 熟悉 Bootloader 的实现过程，能够独立完成基于 USB 的上位机到 MCU 的升级过程，能够用 C++ 实现基本的上位机需求改动及问题调试。

      - layout: left
        title: "个人能力"
        description: |
          - 能够基于中/英文技术文档，独立的对外设进行开发及调试。
          - 具有一定的硬件设计能力，能够设计原理图，常见芯片的焊接，PCB 调试，基本硬件问题的查找及修改。
          - 具有复杂多芯片方案经验，能够主导项目流程，包括软件架构设计，带领团队（包括测试、iOS、Android 开发、固件开发）实现项目量产。
          - 具有快速定位问题、分析问题、解决问题的能力。
          - 具有持续的学习能力，包括使用 ChatGPT、GitHub 等辅助工具。
          - 能够实现一般的算法及调试。
          - 熟练使用 Git 项目管理，VSCode、Eclipse、Keil、Altium Designer 等专业软件。
          - 有个人独立的代码库（多年经验总结、亲自调试的通用模块）。
          - 具备一定的代码分层能力，实现低耦合的模块接口。

  - title: 教育背景 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 河南理工大学
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: "自动化   本科"
        caption: 2011年9月 - 2015年6月
        # quote: >
          # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          多次获得奖学金，积极参加学院实验室工作。

          全国大学生电子设计大赛省级三等奖。
  - title: 项目经历 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "W4 Pro翻译耳机"
        caption: 2023年8月 - 2025年3月
        # sub_title: BSc Computer Science
        quote: >
          项目负责人，从0到1，主导了从需求分析、方案设计、开发实现到量产交付的全过程，成功实现了基于杰理7016平台的翻译耳机产品的量产交付。
        description: | # this will include new lines to allow paragraphs
          - 负责项目的整体规划和管理，协调跨部门团队（包括产品、APP、硬件、算法、生产）高效协作，确保项目按时交付。
          - 基于杰理7016平台，实现了基本tws耳机功能，包括LED、 触摸、 提示音等UI配置，智能仓充电， ota，ENC, 入耳检测，BT配置等 。
          - 基于pipline搭建音频流，实现了音视频翻译、电话翻译、同传翻译功能。
          - 基于ble协议，实现了和app的稳定通信，bt传输音频的同时，ble传输多路opus压缩后的翻译音频。
          - 协助实现算法的移植、死机问题排查、线程资源优化、双核资源分配。
          - 开发了充电舱配套方案，区别于普通充电舱的分果果方案，深度开发了充电、关机、开机流程。
          - 开发了产测方案，包括串口方式传输各类测试指令，ble传输音频到兆华设备，3mic校准，生产烧录的导入，蓝牙认证等。
          - 基于AES加密，通过写入认证码的方式，开发了算法认证加密方案，保护了算法的安全性。
          - 其它，包括功耗优化、性能优化（Android、iOS连接速度、通信稳定性、算法异步处理等），场景切换中的断连问题、死机问题，实现了稳定的翻译功能。
      - layout: left
        title: "W4 翻译耳机"
        caption: 2025年3月 - 2025年11月
        # sub_title: BSc Computer Science
        quote: >
          项目负责人，W4 Pro耳机的升级迭代。
        description: | # this will include new lines to allow paragraphs
          - 添加骨导芯片，实现iis 、 tdm驱动开发，打通骨导音频流，确保骨导音频正确传输给算法。
          - 由于iis时钟和pdm时钟的误差， 开发了对齐算法，确保二者音频差值在8ms内。
          - 开发pdm驱动，原厂驱动输出声音小， 深入驱动内部调节pdm增益。
          - 开发通过串口方式，实现4路（16khz)音频导出，配合算法开发调试。
          - SDK从v1升级到v3, 遇到重大内核问题，协助原厂排查，升级SDK。
          - ble连接概率断联问题，排查到天线问题和SDK问题。
          - 接入双路opus算法，开发了双路opus的传输方案，降低带宽压力，提升翻译稳定性。
          - 开发压测用例，通过工具实现自动化压测，解决低概率断联问题， 实现连续压测60小时无断联。
      - layout: left
        title: "X1 Pro翻译耳机"
        caption: 2025年11月 - 2026年5月
        # sub_title: BSc Computer Science
        quote: >
          项目负责人，W4耳机裁剪方案， 单ble功能。
        description: | # this will include new lines to allow paragraphs
          - 裁剪BT模块，去掉BT可发现、可连接功能， 保留tws连接用于双bank升级。
          - 保留ble翻译模块， 适配翻译主机，优化ble连接速度， 功耗续航。
          - 开发通信协议，实现串口通信，开盖即连接ble，入舱判断tws是否组队，组队后才进入ota流程。
          - 开发新的充电方案，去掉智能仓功能， 适配普通充电仓，同时具有串口通信功能。
          - 开发新的骨导芯片方案，调试tdm驱动，打通音频流，测试稳定性导入到算法端。
          - 开发新的产测方案，mic测试、spk测试、骨导测试。
          - 开发ble dtm认证方案，通过小牛与CWM500连接射频测试，遇到接收丢包（PER)概率失败问题，定位到芯片问题。
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
